---
- hosts: default
  remote_user: vagrant
  become: yes
  become_method: sudo
  vars:
    http_port: 80
    db_root_password: toor_bd
  roles:
    - common
    - nginx
    - docker
    - port_finder
    - role: mysql
      mysql_root_password: "{{ db_root_password }}"
    - role: postgresql
      root_password: "{{ db_root_password }}"
    - redis
