---
- name: Ensure databse exists
  postgresql_db: name={{ app_name }}
  become: yes
  become_user: postgres
- name: Ensure user has access to the DB
  postgresql_user: db={{ app_name }} name={{ app_name }} password={{ app_name }}_password priv=ALL
  become: yes
  become_user: postgres
- name: Ensure user does not have unnecessary privilege
  postgresql_user: name={{ app_name }} role_attr_flags=NOSUPERUSER,NOCREATEDB
  become: yes
  become_user: postgres
