---
- name: Common - ensure libraries are up to date
  apt:
    name: '{{ item }}'
    state: latest
    update_cache: yes
  with_items:
    - libpq-dev
    - python3-pip
- name: Common - ensure PIP extensions are up to date
  pip:
    name: '{{ item }}'
    state: latest
  with_items:
    - psycopg2-binary
