---
- name: Docker - ensure libs needed to use HTTPS repos are installed
  apt:
    name: '{{ item }}'
    state: latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
- name: Docker - add Docker’s official GPG key
  command: bash -c 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -'
- name: Docker - add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
- name: Docker - ensure docker components are installed and at the latest version
  apt:
    name: docker-ce
    state: latest
    update_cache: yes
- name: Docker - ensure docker-compose components is installed and at the latest version
  pip:
    name: docker-compose
    state: latest
- name: Docker - check if Docker group exists
  group:
    name: docker
    state: present
- name: Docker - add vagrant user to docker group
  user:
    name: vagrant
    groups: docker
